package(default_visibility = ["//shipshape:default_visibility"])

load("/tools/build_rules/genproto", "proto_library")

proto_library(
    name = "source_context_proto",
    gen_go = 1,
    gen_java = 1,
)
