package(default_visibility = ["//shipshape:default_visibility"])

load("//tools/build_rules/go", "go_library")

go_library(
    name = "docker",
    srcs = [
        "docker.go",
    ],
    deps = [
        "//third_party/go-glog:go-glog",
    ],
)
