package(default_visibility = ["//shipshape:default_visibility"])

load("//tools/build_rules/go", "go_library")

go_library(
    name = "httpencoding",
    srcs = [
        "httpencoding.go",
    ],
)
